site_name: 我的演算法筆記
site_url: https://WuPinLiang.github.io/Algo-Note/

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - content.code.copy

nav:
  - 首頁: index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
